Repository lablab-ai/community-content, pull requests merged in 2023-09, with the labels that each got.

#209 chatgpt plugin tutorial
  tutorials/chatgpt-plugin-tutorial.mdx
Labels: READY TO PUBLISH

#266 SuperAGI tutorial: Generate a codebase and push it to GitHub
  tutorials/superagi-tutorial-generate-a-codebase-and-push-it-to-github.mdx
Labels: READY TO PUBLISH

#298 Feliciien patch 5
  tutorials/autogpt-tutorial-how-to-use-and-create-agent-for-coding-game.mdx
Labels: REVISION

#306 Create auto-gpt-advanced-tutorial-creating-ai-generated-linkedin-cont…
  tutorials/auto-gpt-advanced-tutorial-creating-ai-generated-linkedin-content.mdx
Labels: 🙋 Bounty claim

#329 AutoGPT-Forge tutorial
  tutorials/auto-gpt-forge-tutorial.mdx
Labels: 🙋 Bounty claim

#348 /claim #294
  tutorials/autogpt-tutorial-creating-a-research-assistant-with-auto-gpt-forge.mdx
Labels: 🙋 Bounty claim
